### ISSUE TITLE
Code denotation is not properly formatted

### ISSUE THREAD

**Issue by luigiistcrazy** [RATIU5/zaggonaut#7]
Poor Rust dev with no idea of frontend here,

I'm trying to get a simple web page up and running where I can post my blog posts and this template looks really cool.

The problem is code doesn't get denoted properly in markdown:

![Image](https://github.com/user-attachments/assets/3c551483-4926-4a61-b555-79631800502c)
(This is on the website)

![Image](https://github.com/user-attachments/assets/080779e6-d9be-4ae5-8aa3-b62dbc3b9a98)
(This is inside the editor)

I tried the same with using the html `<code></code>` tag, however that produces the same output as in the first picture.

Code blocks work without issues though.

**Comment by RATIU5** [comment]
Hey @luigiistcrazy! Thanks for opening an issue.

So the theme's default settings is to actually include the backticks (``) when writing inline styles in markdown.

If you want to remove them for your theme, you'll need to add the following code to the end of `./src/styles/global.css`:

```css
.prose {
  :where(code):not(:where([class~="not-prose"],[class~="not-prose"] *))::before {
    content: none;
  }
  :where(code):not(:where([class~="not-prose"],[class~="not-prose"] *))::after {
    content: none;
  }
}
```
